standalone_tags:
  [
    {id: 0, size: 0.160, name: 'tag_0'},
    {id: 1, size: 0.160, name: 'tag_1'},
    {id: 2, size: 0.160, name: 'tag_2'},
    {id: 3, size: 0.160, name: 'tag_3'},
    {id: 4, size: 0.160, name: 'tag_4'},
    {id: 5, size: 0.160, name: 'tag_5'},
    {id: 6, size: 0.160, name: 'tag_6'},
    {id: 7, size: 0.160, name: 'tag_7'},
    {id: 8, size: 0.160, name: 'tag_8'},
    {id: 9, size: 0.160, name: 'tag_9'},
    {id: 10, size: 0.160, name: 'tag_10'},
    {id: 11, size: 0.160, name: 'tag_11'},
    {id: 12, size: 0.160, name: 'tag_12'},
    {id: 13, size: 0.160, name: 'tag_13'},
    {id: 14, size: 0.160, name: 'tag_14'},
    {id: 15, size: 0.160, name: 'tag_15'},
    {id: 16, size: 0.160, name: 'tag_16'},
    {id: 17, size: 0.160, name: 'tag_17'}
  ]
tag_bundles:
  [
  ]
